<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>QuantAnalyst.Bench</RootNamespace>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\QuantAnalyst.Analytics\QuantAnalyst.Analytics.csproj" />
    <ProjectReference Include="..\..\src\QuantAnalyst.Native\QuantAnalyst.Native.csproj" />
  </ItemGroup>

</Project>
