#!/usr/bin/env python3
"""Write samples/synthetic-prices.csv: SYNTHETIC two-factor GBM prices for demos and CLI tests.

Not market data. Instrument names are deliberately fictitious (SYN-*). Seeded and reproducible.
Usage: python tools/reference/make_synthetic_prices.py
"""
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
SEED = 20260925
DAYS = 260

rng = np.random.default_rng(SEED)
dates = np.busday_range = np.arange(np.datetime64("2025-01-02"), np.datetime64("2026-06-30"), dtype="datetime64[D]")
dates = dates[np.is_busday(dates)][:DAYS]
market = rng.normal(0.0003, 0.011, DAYS)
sector = rng.normal(0.0, 0.007, DAYS)
names = ["SYN-A", "SYN-B", "SYN-C", "SYN-D", "SYN-INDEX"]
beta = np.array([1.2, 0.9, 0.6, 1.0, 1.0])
sector_load = np.array([1.0, 0.8, -0.2, 0.0, 0.0])
idio = np.array([0.012, 0.010, 0.008, 0.015, 0.0])
start = np.array([74.5, 251.3, 118.2, 32.9, 2450.0])
rets = market[:, None] * beta + sector[:, None] * sector_load + rng.normal(0.0, 1.0, (DAYS, 5)) * idio
prices = start * np.exp(np.cumsum(rets, axis=0))

lines = ["# SYNTHETIC data generated by tools/reference/make_synthetic_prices.py (seed %d). Not market data." % SEED,
         "date," + ",".join(names)]
for d, row in zip(dates, prices):
    lines.append(str(d) + "," + ",".join(f"{p:.2f}" for p in row))
(ROOT / "samples").mkdir(exist_ok=True)
(ROOT / "samples/synthetic-prices.csv").write_text("\n".join(lines) + "\n")
print(f"wrote samples/synthetic-prices.csv ({DAYS} rows)")
