#!/usr/bin/env python3
"""Generate independent reference values for the Phase 2 C++ tests (never used at runtime).

Outputs (committed):
  native/src/qe/core/sobol_joe_kuo.inc      Joe-Kuo Sobol direction numbers (first 64 dimensions)
  tests/native/reference/phase2_reference.inc  expected values from numpy / scipy / scikit-learn

Usage (from the repo root, in a venv with numpy, scipy, scikit-learn):
  python tools/reference/phase2_reference.py

Everything is seeded; re-running with the same library versions reproduces the files exactly.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

import numpy as np
import scipy
import scipy.stats
import sklearn
from scipy.cluster.hierarchy import linkage
from scipy.spatial.distance import pdist
from scipy.stats import norm, qmc
from sklearn.covariance import LedoitWolf

ROOT = Path(__file__).resolve().parents[2]
SEED = 20260925
SOBOL_DIMS = 64


def fmt(x: float) -> str:
    r = repr(float(x))
    return r if ("e" in r or "." in r or "inf" in r or "nan" in r) else r + ".0"


def arr(name: str, values, ctype: str = "double") -> str:
    flat = np.asarray(values).ravel()
    body = ", ".join(fmt(v) if ctype == "double" else str(int(v)) for v in flat)
    return f"inline constexpr {ctype} {name}[] = {{{body}}};\n"


def header(what: str) -> str:
    return (
        "// GENERATED by tools/reference/phase2_reference.py - do not edit by hand.\n"
        f"// {what}\n"
        f"// numpy {np.__version__}, scipy {scipy.__version__}, scikit-learn {sklearn.__version__}, "
        f"python {sys.version.split()[0]}, seed {SEED}\n"
    )


# ---------------------------------------------------------------------------------------------
# Sobol direction numbers (Joe & Kuo, new-joe-kuo-6.21201, as shipped inside scipy)
# ---------------------------------------------------------------------------------------------
def sobol_table() -> str:
    path = os.path.join(os.path.dirname(scipy.stats.__file__), "_sobol_direction_numbers.npz")
    data = np.load(path)
    poly, vinit = data["poly"][:SOBOL_DIMS], data["vinit"][:SOBOL_DIMS]
    width = int(max(int(p).bit_length() - 1 for p in poly))
    width = max(width, 1)
    out = header("Joe & Kuo (2008) Sobol direction numbers, new-joe-kuo-6.21201, first 64 dimensions, "
                 "read from scipy/stats/_sobol_direction_numbers.npz.")
    out += "// Dimension 0 is the van der Corput sequence (poly 1). poly encodes the primitive polynomial\n"
    out += "// including leading and trailing 1 bits; degree = bit_length(poly) - 1; m holds the initial\n"
    out += "// direction integers m_1..m_degree (zero padded).\n"
    out += "#pragma once\n\n#include <cstdint>\n\nnamespace qe::core::sobol_data {\n\n"
    out += f"inline constexpr int kDims = {SOBOL_DIMS};\n"
    out += f"inline constexpr int kMaxDegree = {width};\n"
    out += arr("kPoly", poly, "std::uint32_t")
    out += arr("kInitialM", vinit[:, :width], "std::uint32_t")
    out += "\n} // namespace qe::core::sobol_data\n"
    return out


# ---------------------------------------------------------------------------------------------
# Independent algorithm implementations used only to produce expected values
# ---------------------------------------------------------------------------------------------
def ewma_cov(x: np.ndarray, lam: float) -> np.ndarray:
    t = x.shape[0]
    w = lam ** np.arange(t - 1, -1, -1, dtype=float)
    w /= w.sum()
    mu = w @ x
    xc = x - mu
    return (xc * w[:, None]).T @ xc


def hrp(cov: np.ndarray) -> tuple[np.ndarray, list[int]]:
    std = np.sqrt(np.diag(cov))
    corr = cov / np.outer(std, std)
    dist = np.sqrt(np.clip((1.0 - corr) / 2.0, 0.0, None))
    link = linkage(pdist(dist, "euclidean"), "single")  # == paper's sch.linkage(dist, 'single')
    n = cov.shape[0]
    order = [int(link[-1, 0]), int(link[-1, 1])]
    while max(order) >= n:
        expanded: list[int] = []
        for i in order:
            if i >= n:
                j = i - n
                expanded += [int(link[j, 0]), int(link[j, 1])]
            else:
                expanded.append(i)
        order = expanded

    def cluster_var(items: list[int]) -> float:
        sub = cov[np.ix_(items, items)]
        ivp = 1.0 / np.diag(sub)
        ivp /= ivp.sum()
        return float(ivp @ sub @ ivp)

    w = np.ones(n)
    clusters = [order]
    while clusters:
        clusters = [c[j:k] for c in clusters for j, k in ((0, len(c) // 2), (len(c) // 2, len(c))) if len(c) > 1]
        for i in range(0, len(clusters), 2):
            c0, c1 = clusters[i], clusters[i + 1]
            v0, v1 = cluster_var(c0), cluster_var(c1)
            alpha = 1.0 - v0 / (v0 + v1)
            w[c0] *= alpha
            w[c1] *= 1.0 - alpha
    return w, order


def crr(s, k, r, q, vol, t, steps, american: bool, call: bool) -> float:
    dt = t / steps
    u = np.exp(vol * np.sqrt(dt))
    d = 1.0 / u
    p = (np.exp((r - q) * dt) - d) / (u - d)
    disc = np.exp(-r * dt)
    j = np.arange(steps + 1)
    prices = s * u ** (steps - j) * d ** j
    values = np.maximum(prices - k, 0.0) if call else np.maximum(k - prices, 0.0)
    for n in range(steps - 1, -1, -1):
        j = np.arange(n + 1)
        prices = s * u ** (n - j) * d ** j
        values = disc * (p * values[:-1] + (1.0 - p) * values[1:])
        if american:
            values = np.maximum(values, (prices - k) if call else (k - prices))
    return float(values[0])


def reference_values() -> str:
    rng = np.random.default_rng(SEED)
    out = header("Expected values for tests/native (numpy/scipy/scikit-learn).")
    out += "#pragma once\n\nnamespace qe::testref {\n\n"

    # Inverse normal CDF.
    probs = np.array([1e-12, 1e-8, 1e-5, 0.001, 0.01, 0.025, 0.05, 0.1, 0.25, 0.4, 0.5, 0.6, 0.75,
                      0.9, 0.95, 0.975, 0.99, 0.999, 1 - 1e-5, 1 - 1e-8])
    out += "// scipy.stats.norm.ppf\n" + arr("kPpfP", probs) + arr("kPpfX", norm.ppf(probs)) + "\n"

    # Sobol points, unscrambled.
    pts = qmc.Sobol(d=8, scramble=False).random(64)
    out += "// scipy.stats.qmc.Sobol(d=8, scramble=False).random(64), row-major 64x8\n"
    out += "inline constexpr int kSobolRefDims = 8;\ninline constexpr int kSobolRefPoints = 64;\n"
    out += arr("kSobolRef", pts) + "\n"

    # Quantiles (linear / type 7).
    qdata = rng.normal(0.0, 1.0, 37)
    qlev = np.array([0.0, 0.01, 0.05, 0.25, 0.5, 0.73, 0.95, 0.99, 1.0])
    out += "// numpy.percentile(data, 100*levels, method='linear')\n"
    out += arr("kQuantileData", qdata) + arr("kQuantileLevels", qlev)
    out += arr("kQuantileExpected", np.percentile(qdata, 100 * qlev, method="linear")) + "\n"

    # Covariance estimators on a correlated T x N sample.
    t, n = 60, 5
    factor = rng.normal(0.0, 0.012, (t, 1))
    loadings = np.array([[1.0, 0.8, 0.5, 0.2, -0.3]])
    x = factor @ loadings + rng.normal(0.0004, 0.008, (t, n))
    lw = LedoitWolf(assume_centered=False).fit(x)
    out += f"inline constexpr int kCovT = {t};\ninline constexpr int kCovN = {n};\n"
    out += "// returns, row-major T x N\n" + arr("kCovReturns", x)
    out += "// numpy.cov(x, rowvar=False) (unbiased)\n" + arr("kCovSample", np.cov(x, rowvar=False))
    out += "// EWMA lambda=0.94, normalized weights, weighted mean removed\n" + arr("kCovEwma094", ewma_cov(x, 0.94))
    out += "// sklearn LedoitWolf(assume_centered=False)\n" + arr("kCovLedoitWolf", lw.covariance_)
    out += f"inline constexpr double kLedoitWolfShrinkage = {fmt(lw.shrinkage_)};\n\n"

    # HRP on an 8-asset two-block covariance.
    t2, n2 = 250, 8
    f2 = rng.normal(0.0, 0.01, (t2, 2))
    l2 = np.array([[1.0, 0.9, 0.8, 0.1, 0.0, 0.1, 0.0, 0.5],
                   [0.0, 0.1, 0.2, 1.0, 0.9, 0.7, 0.8, 0.5]])
    x2 = f2 @ l2 + rng.normal(0.0, 0.006, (t2, n2)) * np.array([1, 1.5, 0.8, 1.2, 2.0, 1.0, 0.7, 1.1])
    cov2 = np.cov(x2, rowvar=False)
    w_hrp, order = hrp(cov2)
    out += f"inline constexpr int kHrpN = {n2};\n"
    out += "// covariance, row-major N x N (numpy.cov of a seeded two-factor sample)\n" + arr("kHrpCov", cov2)
    out += "// Lopez de Prado (2016) HRP with scipy single linkage\n" + arr("kHrpWeights", w_hrp)
    out += arr("kHrpOrder", order, "int") + "\n"

    # CRR lattice (independent numpy implementation).
    out += "// numpy CRR: S=100 K=110 r=0.03 q=0.01 vol=0.25 T=1.5, 500 steps\n"
    out += f"inline constexpr double kCrrAmericanPut500 = {fmt(crr(100, 110, 0.03, 0.01, 0.25, 1.5, 500, True, False))};\n"
    out += f"inline constexpr double kCrrEuropeanPut500 = {fmt(crr(100, 110, 0.03, 0.01, 0.25, 1.5, 500, False, False))};\n"
    out += f"inline constexpr double kCrrAmericanCall500 = {fmt(crr(100, 110, 0.03, 0.01, 0.25, 1.5, 500, True, True))};\n"
    out += "\n} // namespace qe::testref\n"
    return out


def main() -> None:
    sobol_path = ROOT / "native/src/qe/core/sobol_joe_kuo.inc"
    ref_path = ROOT / "tests/native/reference/phase2_reference.inc"
    ref_path.parent.mkdir(parents=True, exist_ok=True)
    sobol_path.write_text(sobol_table())
    ref_path.write_text(reference_values())
    print(f"wrote {sobol_path.relative_to(ROOT)} and {ref_path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
