# qe_detect_rid(<out_var>): .NET runtime identifier for the target platform (win-x64, linux-x64, ...).
function(qe_detect_rid out_var)
    if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
        set(_os win)
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        set(_os linux)
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
        set(_os osx)
    else()
        message(FATAL_ERROR "Unsupported system for RID detection: ${CMAKE_SYSTEM_NAME}")
    endif()
    string(TOLOWER "${CMAKE_SYSTEM_PROCESSOR}" _proc)
    if(_proc MATCHES "^(x86_64|amd64)$")
        set(_arch x64)
    elseif(_proc MATCHES "^(aarch64|arm64)$")
        set(_arch arm64)
    else()
        message(FATAL_ERROR "Unsupported processor for RID detection: ${CMAKE_SYSTEM_PROCESSOR}")
    endif()
    set(${out_var} "${_os}-${_arch}" PARENT_SCOPE)
endfunction()
